### PR TITLE
Timeless isle scripted & SQL

### PR DESCRIPTION
**Pull request by Crypticaz**
Ignore 

Timeless isle npc with scripts sql

### CODE REVIEW

**Comment by cooler-SAI** [comment]
This branch has conflicts that must be resolved

**Comment by cooler-SAI** [comment]
Conflicting files
sql/updates/world/Death Adder.sql
sql/updates/world/Ironfur Great Bull.sql

**Comment by cybrann** [comment]
Why .sql files like this? Put them all in 1 file and do not make that much delete from and insert queries. That can be done in just 1 query.

**Comment by cybrann** [comment]
I will close this, as I will do the timeless isle scripts, and this pull request is very bad.

**Pull request closed without merging**
